id: P002952
initial_creation_type: ocr
source_metadata:
  id: bdr:W27884
  title: འཇིགས་མེད་རྒྱལ་བའི་མྱུ་གུའི་རྣམ་ཐར
  author: ''
  volumes:
    9e5fd63f07fa4047a826b91ae968751b:
      image_group_id: I4683
      title: ''
      volume_number: 1
      total_pages: 328
