id: I1F59BFC9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:15:39+00:00'
last_modified: '2022-06-07T16:31:18.139532+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27884
  title: འཇིགས་མེད་རྒྱལ་བའི་མྱུ་གུའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4BE5:
      image_group_id: I4683
      title: ''
      total_pages: 328
      order: 1
      base_file: 4BE5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
